### ISSUE TITLE
感谢！

### ISSUE THREAD

**Issue by i-iooi-i** [zhaohaodang/ghost-theme-tiny#1]
超爱大佬的这款主题，感谢！已经是使用中了，现在有个疑问，后续会添加Tag数量统计的功能吗，现在的Tag似乎是没有任何作用的存在。再次感谢！

**Comment by zhaohaodang** [comment]
首先感谢你的青睐。
当我看到这条issues的时候，这个主题的版本已经不适合ghost的最新版本了。
于是我花了一些时间修改了主题，适配了ghost v4版本，同时新增了标签页，包含标签数量，标签列表，标签文章数三个基本信息。
欢迎使用。https://github.com/zhaohaodang/ghost-theme-tiny/releases/tag/2.0.0

**Comment by i-iooi-i** [comment]
嗯嗯。再次感谢，已经用上辽，为能使用上这样简洁不花哨的主题感到开心！
