### ISSUE TITLE
新的主题似乎会导致图片拉伸。

### ISSUE THREAD

**Issue by tommy980226** [zhaohaodang/ghost-theme-tiny#2]
HI，你好。

我开始使用您这款主题，我安装了最新的Ghost 4.0，发现文章内的图片会出现了拉伸问题。
![Snipaste_2021-06-06_05-03-38](https://user-images.githubusercontent.com/85416204/120905462-c3545a00-c684-11eb-9014-278fbd7ad816.jpg)
![Snipaste_2021-06-06_05-04-42](https://user-images.githubusercontent.com/85416204/120905464-c6e7e100-c684-11eb-9a28-29da61800d84.jpg)
我不确定是设置问题还哪里做的不够好导致的这个问题。
不过，还是第一时间过来反馈一下。
打扰，谢谢啦。

![Snipaste_2021-06-06_05-06-47](https://user-images.githubusercontent.com/85416204/120905507-0282ab00-c685-11eb-8f69-99441d33247f.jpg)
对了，似乎还有一个小问题，当后台设置为夜间模式的时候，顶部栏会无法改变颜色。
再次感谢。🙇‍

**Comment by zhaohaodang** [comment]
图片拉伸问题已解决，用最新的包 https://github.com/zhaohaodang/ghost-theme-tiny/releases/tag/2.0.1

**Comment by tommy980226** [comment]
感谢大佬耐心的维护与更新，安装测试了一下，又可以愉快的使用辽。
